### ISSUE TITLE
Please support serve specified file for not found path (useful for single page apps)

### ISSUE THREAD

**Issue by J-F-Liu** [TheWaWaR/simple-http-server#10]
Like the `--entry-file` parameter of [live-server](https://github.com/tapio/live-server).

**Comment by TheWaWaR** [comment]
How about rename it to `--file-404` ? I think `--entry-file` is not that accurate.

**Comment by J-F-Liu** [comment]
I think nginx has a better name for this: `try_files`, so can name it `--try-files` or `--try-file`.

**Comment by TheWaWaR** [comment]
Added in `0.4.5`, https://github.com/TheWaWaR/simple-http-server/commit/7c55731fc1be601925af66bcfb9e0a6e48c07876

**Comment by J-F-Liu** [comment]
Thanks, it's working.
