### ISSUE TITLE
Uploads time out on large files

### ISSUE THREAD

**Issue by NeoTheFox** [TheWaWaR/simple-http-server#102]
Uploading anything large, say, 4 gigs file causes the browser to spew ERR_CONNECTION_RESET error. 
I suspect it might have something to do with Irons [Timeouts](https://docs.rs/iron/latest/iron/struct.Timeouts.html), the default is set to 30 seconds, putting a hard limit on upload size.
Possible solutions are:
 * Disable the timeout entirely
 * Introduce a timeout command line argument
 * Dynamically adjust timeout based on average upload speed times upload size. This one is elegant but involves a guessing game.

**Comment by TheWaWaR** [comment]
I may choose case 2 since it is easy to implement and provide some flexibility.

**Comment by TheWaWaR** [comment]
Did you specified the upload size limit? The default value is less than 8MB, and will case the program panic.

**Comment by kesipyc** [comment]
It works for me.
I've just uploaded 9GB file, that took over 9 min through WIFI. I did use "-l" to set limit to 1TB. I'm on Windows x86_64 0.6.8.

**Comment by TheWaWaR** [comment]
I think it's already fixed in https://github.com/TheWaWaR/simple-http-server/commit/0806b006b9ea1388e551ce1af84b01db9e909fcb 

Please comment below if you still have the same problem.
