### ISSUE TITLE
How to use on linux

### ISSUE THREAD

**Issue by samTime101** [TheWaWaR/simple-http-server#104]
what to download and how to use it
![Screenshot from 2024-01-29 00-01-05](https://github.com/TheWaWaR/simple-http-server/assets/116491957/3eec57a9-f5c1-45d0-8703-b5972ce839fd)

**Comment by Ijustplaymc** [comment]
depends on what ur running it on

if ur using a standard x86 pc (amd or intel, generic) use
x86_64-unknown-linux-musl-simple-http-server

simply wget that into a small dir containing your html files

now chmod it to work (chmod +x ./<filename>)

now to run simply do

./<filename> (as sudo if that doesnt work, if its installed)
