### ISSUE TITLE
Downloading files with space in name fails

### ISSUE THREAD

**Issue by CY-Pan** [TheWaWaR/simple-http-server#105]
I've been using this great tool for some time to move files from my laptop to my Android device. One day I found some of the files just disappear from my Android Chrome's list during downloading, without any success message or failure warning. After several tests, I find this problem occurs on file with space in its name, such as "Sample 1.mp4".

I know the problem of file disappearing should be bugs in Chrome. But I'm curious on the downloading procedure of this tool. When I download a large file through this tool, the client first sends request to the server and gets 200 reply. But later, it seems to request the file again and gets 206 reply.
![Snipaste_2024-02-23_10-02-28](https://github.com/TheWaWaR/simple-http-server/assets/59761962/b69fe82e-0a77-4b35-b549-4c2a9f76e5af)

On the contrary, if I download the file through Python's http server, it's only one request and one reply. (Both cases are tested with same Android Chrome)
![Snipaste_2024-02-23_10-07-19](https://github.com/TheWaWaR/simple-http-server/assets/59761962/23a0da96-90a2-4e49-bbb6-ba3b42978d2b)

I'm wondering why their download processes differ in this way. Also, through observation, I found the download issue occurs at the time the client requests the file again and gets 206 reply. Is there possibly a command option to make this tool behave like Python's http server with exactly 1 request and 1 reply?

**Comment by TheWaWaR** [comment]
HTTP code 206 is a `Partial Content success status`. If you want disable it, just passing `--norange` in command line argument.
