### ISSUE TITLE
Add a option to diable the coloring log

### ISSUE THREAD

**Issue by tonyho** [TheWaWaR/simple-http-server#114]
When I use a script to handle the output, the colored log would introduce some problems when handling the output string. I think it's better to have a option to control(disable/enable) the coloring for the output log.

Thanks.

**Comment by TheWaWaR** [comment]
Fixed in: https://github.com/TheWaWaR/simple-http-server/commit/4e05b9f05098522f51ca9ed70fa6ed920af40f57
