### ISSUE TITLE
content-type invalid for HEAD requests

### ISSUE THREAD

**Issue by clementnuss** [TheWaWaR/simple-http-server#124]
the content type for `HEAD` request is hardcoded to be `text/plain` ([here](https://github.com/TheWaWaR/simple-http-server/blob/master/src/main.rs#L921)).

this prevents my server from booting an iso file, as it (rightfully) expects a `application/octet-stream` content-type, and doesn't proceed when that isn't the case.

could you somehow reuse the logic the for `GET` request (which is working properly with the guess_mime) so that the same happens for `HEAD` requests ?

**Comment by TheWaWaR** [comment]
Fixed in: https://github.com/TheWaWaR/simple-http-server/commit/6de5a6f002cbbbd6b89f9a8c503de4f55a78e3c9
