### ISSUE TITLE
Sensitive information disclosure

### ISSUE THREAD

**Issue by goecho** [TheWaWaR/simple-http-server#13]
Readable to /etc/passwd file
http://your-ip/..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2fetc/passwd

**Comment by goecho** [comment]
Proposes to prevent access to non-web directories

**Comment by TheWaWaR** [comment]
I think you shouldn't run simple-http-server in `/etc`

**Comment by goecho** [comment]
I think it doesn't matter where it runs, it's a security hole.

**Comment by TheWaWaR** [comment]
The permission of `/etc/passwd` is `-rw-r--r--` whatever a normal user can read the file, why `simple-http-server` run by current user can't read the file?

**Comment by goecho** [comment]
The behavior of using other web-servers is different from it

**Comment by TheWaWaR** [comment]
But nginx can do that, https://serverfault.com/questions/588770/why-can-nginx-access-etc-pass

**Comment by alecdwm** [comment]
I think simple-http-server is breaking user expectations by serving files above the current working directory.

For python's http.server, `http://localhost:8000/..%2f` will map to `$(cwd)/`.
Whereas for simple-http-server, `http://localhost:8000/..%2f` will map to `$(cwd)/../`.

A user who is not aware of this will be accidentally exposing their system to the network, particularly when they have the `--upload` flag enabled.

**Comment by Kinrany** [comment]
I also expected simple-http-server to only serve the current working directory. Is that really not the case?

**Comment by Avi-D-coder** [comment]
Serving files above the path the server was invoked in/with is a major security issue. @TheWaWaR  This issue should be reopened. I will fix it today.

**Comment by TheWaWaR** [comment]
Sorry, it's definitely a serious problem.

**Comment by Avi-D-coder** [comment]
Fixed in https://github.com/TheWaWaR/simple-http-server/pull/35

**Comment by Avi-D-coder** [comment]
I could use a windows tester for https://github.com/TheWaWaR/simple-http-server/pull/35#discussion_r318997500

**Comment by Kinrany** [comment]
Thanks :D
