### ISSUE TITLE
Does not handle files with `?` or other special characters in name

### ISSUE THREAD

**Issue by robinst** [TheWaWaR/simple-http-server#2]
1. Create a file named "url?encoding&test%test" in a directory
2. Start `simple-http-server`
3. Click on the file

Expected: It shows the file
Actual: 404, because the link was "http://localhost:8008/url?encoding&test%test" instead of being URL-encoded.

Looks like it's not URL-encoding file names. This is with 0.3.4 that I installed just now via `cargo install`.

**Comment by TheWaWaR** [comment]
Thanks, seems fixed now.

You may update by: `cargo install --force simple-http-server`

**Comment by robinst** [comment]
Works now, thanks!
