### ISSUE TITLE
[feature] add mime type bindings by command line

### ISSUE THREAD

**Issue by kawogi** [TheWaWaR/simple-http-server#20]
While experimenting with WebAssembly I found that (at least in Firefox) WebAssembly.instantiateStreaming() requires `.wasm`-resources to be delivered as `application/wasm`. Otherwise you end up with "TypeError: Response has unsupported MIME type".

Since `application/wasm` doesn't seem to be official, yet (https://www.iana.org/assignments/media-types/media-types.xhtml#application) I cannot expect `simple-http-server` to include this binding.

It would be helpful to be able to add bindings between file extensions and mime types via command line.

**Comment by David-OConnor** [comment]
Rust leads in WASM support, so WASM-support out of the box, without extra config, is something that would be nice from a Rust-based server.

**Comment by dakom** [comment]
@David-OConnor it seems to me that for wasm suport in particular, it's only a matter of upgrading the `mime_guess` dependency. Unless I'm mistaken wasm was added a _long_ time ago: https://github.com/abonander/mime_guess/commit/a0e193ecc22e217b140b83096e01c19f72b90baa

@TheWaWaR can you please bump `mime_guess`?

**Comment by David-OConnor** [comment]
Yeah, I think it was! (My post was also from a long time ago)

**Comment by TheWaWaR** [comment]
Fixed in https://github.com/TheWaWaR/simple-http-server/commit/1c81c851ae149819627402b016d2665d80755386 .

[New version](https://crates.io/crates/simple-http-server/0.6.1) published.
