### ISSUE TITLE
Become `wget -m`-friendly

### ISSUE THREAD

**Issue by chrysn** [TheWaWaR/simple-http-server#3]
One typical application for Python's `http.server` is quickly getting several files over ad-hoc networks in combination with wget. For this to work well even across resumptions, I'd suggest to implement

* Sending Last-Modified
* Replying 304 to If-Modified-Since
* Parse Range / serve Accept-Ranges and Content-Range

Possibly, this is something that should be delegated to Iron's `Modifier<Response>` implementation for `Path`, or another generic "respond from file" mechanism.

**Comment by TheWaWaR** [comment]
Cache control implemented, `Range` is on the way.

**Comment by TheWaWaR** [comment]
@chrysn 
Cache and partial request support all added!
