### ISSUE TITLE
Bump version

### ISSUE THREAD

**Issue by aochagavia** [TheWaWaR/simple-http-server#4]
Version `0.3.6` fails to compile on Windows because of a `use std::os::unix::ffi::OsStrExt;`. This is fixed in the master branch but in the meantime it makes it impossible to do `cargo install simple-http-server`.

**Comment by TheWaWaR** [comment]
`0.3.7` just published, please have a try.

**Comment by TheWaWaR** [comment]
Tested on windows 7 32bit, though console color is not fixed yet.
