### ISSUE TITLE
 LAN Gigabit network download test

### ISSUE THREAD

**Issue by QQ2017** [TheWaWaR/simple-http-server#42]
After several times of LAN Gigabit network test download 10G single file, the download speed is never reached the limit, the speed is about 60-80MB / s, but I use the go language version of the HTTP server, the speed can reach the hardware limit, the speed is about 98MB /s, and the speed is very stable.
For example this HTTP SERVER: https://github.com/stewart/http-server
Is it a question of programming language efficiency? Is there room for improvement? Because the go language program is too large, I don't want to use it.

**Comment by TheWaWaR** [comment]
I guess it's because the implementation of [hyper](https://crates.io/crates/hyper)
