### ISSUE TITLE
Version from cargo and released bin is unsecure!

### ISSUE THREAD

**Issue by markus-geiger** [TheWaWaR/simple-http-server#45]
http://x.x.x.x/%2F is possible! No problem to retrieve ro-files from /etc. 

Also would be nyce to see a https-only and an autogenration for self-signed certs.

**Comment by notthetup** [comment]
Indeed! The only latest version published to crates.io seems to be 0.4.7 https://crates.io/crates/simple-http-server

Similarly with `releases` section of Github. https://github.com/TheWaWaR/simple-http-server/releases

**Comment by blurayne** [comment]
Version from master states 0.6 and does solve the problem (also when you start with cert it's https).

But this insecurity should be flagged and cargo releases should be updated.

**Comment by TheWaWaR** [comment]
0.6.0 published. Please update simple-http-server though `cargo install simple-http-server --force`

I only have Linux machine, will upload the binary in release page later.
