### ISSUE TITLE
Question: How to use --cert option ?

### ISSUE THREAD

**Issue by patrickelectric** [TheWaWaR/simple-http-server#48]
There is not instructions in the repository, and all method that I have tried failed with random error messages:
such as: `Tls(Error { code: -25264, message: "MAC verification failed during PKCS12 import (wrong password?)" })'`

methods:
https://gist.github.com/Eng-Fouad/6cdc8263068700ade87e4e3bf459a988
https://gist.github.com/princeppy/d00bad66d9caac86d9b7d3ce9e35fc12

Is it possible to add somewhere how such desired pkcs12 file could be generated ?

**Comment by TheWaWaR** [comment]
You can try [this method](https://serverfault.com/a/831442) to generate a self-signed certificate.

Then 
```
$ simple-http-server --cert ./keyStore.p12 --certpass {YourPassword}
```

**Comment by TheWaWaR** [comment]
Any feedback? I'm going to close this issue if no comment last for a week since today.

**Comment by patrickelectric** [comment]
Thanks, it works!
