### ISSUE TITLE
HTML Templates

### ISSUE THREAD

**Issue by gsquire** [TheWaWaR/simple-http-server#5]
Have you considered using templates for your HTML? The [maud](https://github.com/lfairy/maud) library integrates with iron quite well. I don't know if it would suit all of your needs but it may be better than handwriting HTML.

**Comment by TheWaWaR** [comment]
I have considered `handlebars`. But template things in this program is very simple, add template dependency will increase compile time and binary size. And `maud` requires nightly to build, which is not acceptable.
