### ISSUE TITLE
🚨 Potential Security Vulnerability

### ISSUE THREAD

**Issue by x3rz** [TheWaWaR/simple-http-server#58]
Hello, @TheWaWaR @vi @not-fl3 @michelk @tforgione  - 2 potential high severity security vulnerability in your repository has been disclosed to huntr.

Visit report URL and validate them
https://www.huntr.dev/bounties/3-other-TheWaWaR/simple-http-server/
https://www.huntr.dev/bounties/2-other-TheWaWaR/simple-http-server/

Best Regards

**Comment by x3rz** [comment]
any Updates?

**Comment by vi** [comment]
@x3rz , I'm not sure simple-http-server with uploading enabled is designed to be exposed to public.
Such things are expected to either be used as an internal filesharing service (where ability to upload HTML/JS applications to be automatically hosted there can be benefitial, even if it is a risk) or as a part of some larger scope solution (where security should be handled not solely by simple-http-server, although it can provide hooks and more fine grained restrictions for that).

In any case, trying to address any of the linked issues may be a significant complication. Disclaimers stating that authentication is not a protected against brute forcing or that file upload allows XSS by default can be added to README and help message although.

**Comment by x3rz** [comment]
@vi Thanks for the reply 
I got it that if you keep these disclaimers in README file then simple-http-server is no longer responsible for any sort of attack as you said it should be used in the internal network but previous I saw a CSRF [report](https://www.huntr.dev/bounties/1-other-simple-http-server/) got validated by one of the maintainers so I took interest in this project to hunt vulnerabilities.
So sir if you think that they are valid vulnerabilities then please validate them.

**Comment by x3rz** [comment]
Any updates Sir ?

**Comment by foodornt** [comment]
this is scary yo

I'm uninstalling simple-http-server rn 

this project is dead as hell

**Comment by TheWaWaR** [comment]
Firstly, thanks for your effort to this project!

Just as `vi` said, for the sake of `simple`, this project is intended to used in internal network, but if used in public network should consider the risk. 

Simple here means:
- the code should be as simple as possible
- the binary size should be as simple as possible
- the compile speed should be as fast as possible
- the usage should be as simple as possible

So, if a vulnerability is fatal, I'll try my best to fix it. If it's not fatal, I'll consider the complexity of fixing it and the 4 above points, if it's simple then fix it.

For `bounties/2`, I will fix it in a simple way: remember about 100 remote ip address and reject frequent http auth verification.

For `bounties/3`, `--upload` to replace a file is a intended feature, and a `--auth` argument can not enable upload functionality.

**Comment by MRAAGH** [comment]
I appreciate the decision to keep this software simple despite having security vulnerabilities which sound scary at first.

I agree that these vulnerabilities are not relevant for the intended use.

Personally, I temporarily start the server when I want to receive large files from friends, and I actively monitor the connections while it is running.
