### ISSUE TITLE
Add arm binary in release

### ISSUE THREAD

**Issue by patrickelectric** [TheWaWaR/simple-http-server#65]
it would be nice to have armv7 and arm64

**Comment by rafrafek** [comment]
That would be great! For Apple devices arm64 is de facto a new standard, and there are many Linux arm users and some Windows arm users as well.

**Comment by TheWaWaR** [comment]
@patrickelectric @rafrafek 
Just added, you may have a try. https://github.com/TheWaWaR/simple-http-server/releases/tag/v0.6.5
