### ISSUE TITLE
OpenSSL vendoring should be optional

### ISSUE THREAD

**Issue by robmv** [TheWaWaR/simple-http-server#69]
I use `simple-http-server` for easy on time sharing of files inside the local network. I don't want to rebuild it for every new security update of OpenSSL. If someone needs it statically linked for some usage inside a container, they can use the `--features` argument of `cargo install`

**Comment by TheWaWaR** [comment]
It seems hyper-native-tls is enough to use simple-http-server inside a container, just removed openssl.
