### ISSUE TITLE
Can you give an example on how to upload using the API?

### ISSUE THREAD

**Issue by mindtricksdev** [TheWaWaR/simple-http-server#73]

**Comment by sysbite** [comment]
Better late then never.

Have a curl sample:
curl -X POST -F "csrf=your_token -F files=@yourfile.ext;filename=path_to_root/yourfile.ext http://<yourip>:<yourport>/save_files_endpoint

**Comment by TheWaWaR** [comment]
And you can get the csrf token from the startup output, some thing like this:
```
Upload: enabled, CSRF Token: *******
```
