### ISSUE TITLE
TLS support is not enabled during compilation of simple-http-server

### ISSUE THREAD

**Issue by Alsan** [TheWaWaR/simple-http-server#84]
I'd like to build and test webcrypto features in a demo, and would like to setup the test environment using this simple http server. I got this message when providing a cert. I download this utils by using `cargo install simple-http-server`. So, how can I recompile it by enabling tls?

**Comment by TheWaWaR** [comment]
Please paste the error message?

**Comment by Alsan** [comment]
exactly as the title.

![2023-03-09_10-43](https://user-images.githubusercontent.com/217947/223902643-c2c8c7d6-9568-4fde-bd56-f640151c9aae.png)
