### ISSUE TITLE
(Help) a brief installation/usage guide

### ISSUE THREAD

**Issue by bheeshmpita** [TheWaWaR/simple-http-server#87]
Please help me by guiding how to use it 
I'm using Linux.

**Comment by mh0s41n** [comment]
Run the program in which folder/directory you want to share. You can copy the program to that directory and run the program from there, or specify the directory through command line argument (see [README.md](https://github.com/TheWaWaR/simple-http-server#command-line-arguments)).

The next step is identifying your device's local IP address. You can do it in numerous ways, I won't bother writing here. [Google it](https://www.google.com/search?q=find+local+ip+address+%3Cos%3E) if you don't know.

Then go to a browser from your target device where you want to download the files to and visit the server device's IP address with the port number `8000`. For example, if your server IP address is `192.168.0.101`, visit `192.168.0.101:8000` from another device and you should see all the items of the directory in which you are running the server.

**Comment by bheeshmpita** [comment]
Thanks Mosharraf for helping out. If you can help further, please guide how to add authorization to access the files.

**Comment by mh0s41n** [comment]
Just pass a command line argument `--auth user:pass` when running the server, where `user` is the username you want, and `pass` is the password. See the [README.md](https://github.com/TheWaWaR/simple-http-server#command-line-arguments) for other options.

**Comment by Kjshinde** [comment]
Hey, can someone help me,
 I am running the server on my Windows PC and I am able to access the server on the same machine using Chrome browser by following your instructions mentioned above. 
But I cannot access the server on my iPhone using Chrome browser using the "server IP address:8000" (I am connected to same network).
