### ISSUE TITLE
0.0.0.0 rather than actual local IP (on Mac Ventura)

### ISSUE THREAD

**Issue by retteghy** [TheWaWaR/simple-http-server#89]
Probably obvious to the dev, but wanted to mention:
http://0.0.0.0:8000 does work on the localhost machine running simple-http-server, but any other devices on the same net would be trying to access themselves. 

It would be ideal if it would display the correct local IP in the terminal output, that would make sharing the IP to other devices also easier.  

see last line:
```
Index: disabled, Cache: enabled, Cors: disabled, Coop: disabled, Coep: disabled, Range: enabled, Sort: enabled, Threads: 3
Upload: disabled, CSRF Token: 
Auth: disabled, Compression: disabled
https: disabled, Cert: , Cert-Password: 
Root: /Users/a/Downloads/_temp,
TryFile404: 
Address: http://0.0.0.0:8000
```

**Comment by da3dsoul1** [comment]
same on windows

**Comment by TheWaWaR** [comment]
`0.0.0.0` is for binding the listening socket on all your network devices, so you can access the server by `127.0.0.1` or `192.168.1.x` or `10.x.x.x` at the same time. If you want bind on a specific IP address, just run `simple-http-server` with that IP address:
```
simple-http-server --ip 192.168.1.x
```
You may want `ifconfig | grep inet` to get the IP address you want to use.
