### ISSUE TITLE
PHP or Lua

### ISSUE THREAD

**Issue by TheShadowModsUK** [TheWaWaR/simple-http-server#96]
Is there anyway to include PHP or Lua I need server side for a basic logging and comment system your tool was the first
tool out of them all that just worked

mongoose  didn't let me set things up right and 
Caddy was just a fire, create file call it Caddyfile caddy exe can't find it no mater what

your tool open up, and it works it's been really helpful so far but I need a way to save data like comment/chat message

**Comment by TheWaWaR** [comment]
Sorry, it's out of the scope.
