### ISSUE TITLE
Future incompatibility with Cargo

### ISSUE THREAD

**Issue by Zeguim** [TheWaWaR/simple-http-server#97]
I installed the dark mode version using:

 cargo install --git https://github.com/yurtaev/simple-http-server --branch="features/dark-mode"

  The installation process went well but at the end I've encountered the following warnings:
  
-----------------------------------------------------------------------------------------------------------------

  warning: use of deprecated method `chrono::TimeZone::timestamp`: use `timestamp_opt()` instead
   --> src\util.rs:136:11
    |
136 |     Local.timestamp(sec, nsec)
    |           ^^^^^^^^^
    |
    = note: `#[warn(deprecated)]` on by default

warning: `simple-http-server` (bin "simple-http-server") generated 1 warning
    Finished release [optimized] target(s) in 2m 20s
warning: the following packages contain code that will be rejected by a future version of Rust: buf_redux v0.8.4, multipart v0.16.1, traitobject v0.1.0
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
  Installing C:

**Comment by TheWaWaR** [comment]
Fixed in https://github.com/TheWaWaR/simple-http-server/commit/9514f99c78e8a42a38572d2a1365aaa0bc2112b9

**Comment by Zeguim** [comment]
Good work!
